spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/authorization-server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 9000

# signkey를 고정하여 서버가 재부팅해도 갱신키 발급이 가능
security:
  oauth2:
    jwt:
      signkey: 123@#$